spring.application.name=JitterTravel
management.endpoints.web.exposure.include=health,metrics
spring.sql.init.mode=always
spring.datasource.url=jdbc:postgresql://localhost:5432/jittertravel
spring.datasource.username=jitter
spring.datasource.password=travel
